config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root 'customers#index'

    resources :customers

    get '/black_list', to: 'customers#black_list', as: 'black_list'

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
# frozen_string_literal: true

class CustomersController < ApplicationController
  before_action :set_customer, only: %w[show edit update]

  def index
    @customers = Customer.all
  end

  def black_list
    if @customer.black_list = false
         @customer.black_list == true
    end
  end
  
  def show; end

  def edit; end

  def update
    if @customer.update(customer_params)
      redirect_to customer_path(@customer)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :phone, :body)
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
# frozen_string_literal: true

module CustomersHelper
end

app/views/customers/_customer.html.erb
<tr>
<% if customer.black_list != true %>
  <td><%= customer.name %></td>
  <td><%= customer.phone%></td>
  <td><%= customer.body%></td>
  <td><%= link_to 'Show', customer_path(customer)%></td>
  <td><%= link_to 'Edit', edit_customer_path(customer)%></td>
  <td>
  <%= link_to 'Man, To Black',
              customer_path(customer),
              method: :black_list,
              data: { confirm: 'Are You sure?' }%>
  </td>   
<% end %>
</tr>

app/views/customers/_form.html.erb
 
<%= form_with model: @customer, local: true do |form| %>
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p> 
    <p>
      <%= form.label :phone %><br>
      <%= form.text_field :phone %>
    </p>   
    <p>
      <%= form.label :body %><br>
      <%= form.text_field :body %>
    </p>   
    <p><%= form.submit%></p>
<% end %>

app/views/customers/edit.html.erb
<p>
  <%= link_to 'List Users', customers_path %>
</p>
<h1>Edit User</h1>
<%= render 'form'%>

app/views/customers/index.html.erb
<h2>List Users:</h2>
  <table>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Body</th>
      <th colspan="3">Actions</th>
    </tr>
  <%= render @customers %> 
  </table>

app/views/customers/show.html.erb
<p>
  <%= link_to 'List Users', customers_path %>
</p>
 
<p>
  <strong>Name</strong>
    <%= @customer.name %>
</p>

<p>
  <strong>Phone</strong>
    <%= @customer.phone%>
</p>

<p>
  <strong>Body</strong>
    <%= @customer.body %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestBlack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>